import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SignupHeader from "@/components/SignupHeader";
import { SignupContextProvider } from "@/contexts/SignupContext";
import { Card } from "@/components/ui/card";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SignupContextProvider>
          <div className="flex justify-center w-full h-[100vh] p-0 items-center">
            <Card className="w-full md:w-10/12 xl:w-8/12 p-0">
              <Card className="p-0 m-0">
                <SignupHeader />
              </Card>
              <Card className="p-4 m-0">
                {children}
              </Card>
            </Card>
          </div>
        </SignupContextProvider>
      </body>
    </html>
  );
}
